### ISSUE TITLE
[Android]Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:19970_4

### ISSUE THREAD

**Issue by yiguozhen0510** [pauldemarco/flutter_blue#450] opened 2019-11-18 03:34 UTC
when i call the connect(),i can't receive the state of bluetooth by used onStateChanged.anyone got this?

**Comment by pauloamaral93** [comment] 2019-11-18 10:45
If you are using Flutter > 1.9 and flutter_blue < 6.0 you will find this problem.

**Comment by yiguozhen0510** [comment] 2019-11-19 01:10
so,What can i do for it?

**Comment by pauloamaral93** [comment] 2019-11-19 09:12
Downgrade flutter or upgrade flutter_blue (breaking changes can happen)

**Comment by d-wolf** [comment] 2019-12-05 11:01
Duplicate of #435 .

**Comment by pauldemarco** [comment] 2020-04-02 08:13
This should be resolved with the recent support for Android v2 embedding.

**Closed by pauldemarco** 2020-04-02 08:13 UTC
